- install_prerequisites/build
Signed-off-by: Damian Rouson <damian@rouson.net>
> Clarify and correct the usage information output by the build --help.

- install_prerequisites/build
Signed-off-by: Damian Rouson <damian@rouson.net>
(cherry picked from commit dd58e76e6f929418410bc08906e68c50d3723ca3)
> Forgot to push Damian's changes in the previous PR

- .travis.yml
- CMakeLists.txt
- README.md
- STATUS.md
- src/tests/integration/CMakeLists.txt
- src/tests/integration/pde_solvers/coarrayBurgers/CMakeLists.txt
- src/tests/integration/pde_solvers/navier-stokes/CMakeLists.txt
- src/tests/performance/BurgersMPI/CMakeLists.txt
Apply changes from PR #71 via `git cherry-pick` to 1.x branch
> Apply changes from PR #71 via cherry-pick to 1.x branch

- .gitattributes
- .pullapprove.yml
- Right now:
- At least one person form SI (@zbeekman, @rouson, @afanfa) must approve a PR
- Approver may be the PR Author
- This is the regexp to match approval via comments:
`'^([Aa]pproved|:\+1:|:shipit:|:ship: it|LGTM|:zap:|:boom:|:clap:|:bow:)'`
- This is the regexp to reject via comment:
`'^([Nn]ope|[Nn]ope\.jpg|[Dd]enied|[Rr]ejected|:\-1:)'`
- Approve or reject at pullapprove.com as well
> Formalize PR code review policy w/ pullapprove.com

- AUTHORS.md
- CAF_ABI.md
- CONTRIBUTING.md
- GETTING_STARTED.md
- INSTALL.md
- README.md
- STATUS.md
> Update markdown files in `devel` to match `master`

- CMakeLists.txt
Distinguish git clones from released version.
> Bump version # to 1.3.1

- src/mpi/mpi_caf.c
As requested by @rouson in #124 .
> Adding comment for duplicates check in sync images

- src/mpi/mpi_caf.c
> Bugfix STOP

- codecov.yml
Codecov.io moved settings to yaml file in repo
> Migrate to codecov.yml

- .travis.yml
- prerequisites/install-functions/build_opencoarrays.sh
- prerequisites/install-functions/find_or_install.sh
- prerequisites/stack.sh
install.sh is still failing silently on ubuntu during Travis-CI... Once #150 is merged/completed, this shouldn't be an issue. For the time being I am going to try to ensure that the build progresses a little bit further for GCC, even though I'm anticipating it will still fail (due to a time out)
> Try to ensure g++-5 exists

- prerequisites/install-functions/report_results.sh
> Add writing of setup.csh for C-shell users.

- Brewfile
- CMakeLists.txt
- developer-scripts/Vagrantfile
- developer-scripts/git-hooks/commit-msg
- developer-scripts/git-hooks/pre-commit
- developer-scripts/git-hooks/pre-push
- developer-scripts/setup-git.sh
- src/tests/unit/sync/CMakeLists.txt
Various tweaks and bug fixes. Specifically #202 should be fixed and issues with OpenMPI being oversubscribed in the test suite.
> Small tweaks

- src/libcaf.h
> Addresses issue 235

- CMakeLists.txt
- src/tests/CMakeLists.txt
- src/tests/integration/pde_solvers/navier-stokes/CMakeLists.txt
Add option to disable tests using FFT library written in assembly.
Fixes #244
> Add option to disable tests with assembly/binary

- src/mpi/CMakeLists.txt
> Support building shared libs

- INSTALL.md
Spring cleaning... add changes from [stale `install-doc-fix` branch](https://github.com/sourceryinstitute/opencoarrays/tree/install-doc-fix)
> Install doc

- install.sh
- prerequisites/install-functions/report_results.sh
Also clean up redundant double slashes in paths in setup.sh.
> Add environment variable definitions in setup.sh

- src/mpi/mpi_caf.c
This pull request removes code complexity and improves readability by replacing conditional compilation blocks by macro calls. The macros contain exactly the same code like the conditional compilation blocks, but are far easier to read and understand.
This pull request replaces #300.
> Reduce code complexity

- .pullapprove.yml
- src/tests/integration/pde_solvers/navier-stokes/CMakeLists.txt
Fixes #318 
Should fix issue reported by @LaHaine. Kudos for catching this.
> Fix bad arg order in CMake command

- .gitattributes
- .github/ISSUE_TEMPLATE.md
- .github/PULL_REQUEST_TEMPLATE.md
- AUTHORS.md
- Brewfile
- CAF_ABI.md
- CONTRIBUTING.md
- GETTING_STARTED.md
- INSTALL.md
- README.md
- STATUS.md
Cleanup and update markdown files, also try to address #29 and add some PR and issue templates
> Update and cleanup markdown files

- .github/ISSUE_TEMPLATE.md
touches
touches
set of changes
Remove tabs and whitespace issues from PR and issue templates
Templates had tabs in them, going against guidelines and messing up rendering of issue template
[links]:#
[contributing guidelines]: https://github.com/sourceryinstitute/opencoarrays/blob/master/CONTRIBUTING.md
[commit message]: https://robots.thoughtbot.com/5-useful-tips-for-a-better-commit-message
[these guidelines]: http://tbaggery.com/2008/04/19/a-note-about-git-commit-messages.html
[Contributor …
> Un-tab-ify issue and PR templates

- .github/ISSUE_TEMPLATE.md
- .github/PULL_REQUEST_TEMPLATE.md
- CONTRIBUTING.md
Add info about coverage, unit tests etc.
touches
touches
set of changes
Tweaked ISSUE and PR template to include average wait time badge and info on code coverage and unit tests
Tweaked CONTRIBUTING.md to have more coverage info and waffle.io issue status info
More complete information for internal and external contributors
[links]:#
[contributing guidelines]: https://github.com/sourceryinstitute/opencoarrays/blob/master/CONTRIBUTING.md
[commit message]: …
> Tweak PR, ISSUE templates and CONTRIBUTING.md

- .github/ISSUE_TEMPLATE.md
- .github/PULL_REQUEST_TEMPLATE.md
- AUTHORS.md
- CAF_ABI.md
- CONTRIBUTING.md
- GETTING_STARTED.md
- INSTALL.md
- README.md
- STATUS.md
- src/tests/integration/pde_solvers/README.md
| --------------------------------- | --------------------------- |
| ![Issue Stats](https://img.shields.io/issuestats/p/github/sourceryinstitute/OpenCoarrays.svg?style=flat-square)   | ![Codecov branch](https://img.shields.io/codecov/c/github/sourceryinstitute/OpenCoarrays/master.svg?style=flat-square) |
touches
touches
set of changes
sourceryinstitute/opencoarrays --> sourceryinstitute/OpenCoarrays
Update the repo name to …
> Update repo name opencoarrays --> OpenCoarrays

- src/extensions/caf-foot
is addressing
touches
touches
changes
set of changes
commit resolves an open issue.
[pullapprove comment] …
> issue-352: support caf --wrapping option 

- .travis.yml
- CMakeLists.txt
Implemented #342, an added advanced option to the CMake build to enable tests with known failures, AKA developer mode. Please add `export OPENCOARRAYS_DEVELOPER=ON` to your  `.bashrc` or `.bash_profile`/`.profile` if you are an @sourceryinstitute or @sourceryinstitute/team-opencoarrays member so that you don't have to remember to pass this flag to CMake.
Homebrew has released GCC 7 and the necessitates rebuilding and repackaging (aka bottling) OpenCoarrays. However, as part of the Homebrew formula build, the build tests are run, and right now, with GCC 7 we have two known failures …
> Urgent bugfix: Issue 342 developer test flag

- prerequisites/install-functions/report_results.sh
Don't use greedy globing in trailing substring removal parameter expansion, and use more  concise, more portable `type -P` to find executables.
Supersedes and closes #386 
See #385 
is addressing
touches
touches
changes
set of changes
commit resolves an open issue.
clicking the "details" …
> Issue 385 fix report_results.sh

- .github/ISSUE_TEMPLATE.md
- .github/PULL_REQUEST_TEMPLATE.md
- CONTRIBUTING.md
Tightened up CONTRIBUTING.md, and issue and PR templates
Templates were too verbose, and it was too annoying to have to click so many check boxes, so people were just ignoring them completely.
is addressing
touches
touches
changes
set of changes
commit resolves an open issue.
clicking the …
> Cleanup templates

- INSTALL.md
Added instructions for installing OpenCoarrays using
- EasyBuild
- Spack
in the Linux section of the INSTALL.md file
Resolves: #387
[links]:#
Added installation instructions for EasyBuild and Spack …
> RFE: Add EasyBuild option in INSTALL.md

- CMakeLists.txt
- GETTING_STARTED.md
- README.md
- developer-scripts/hpclinux-install.sh
- developer-scripts/patched-trunk-install.sh
- prerequisites/install-functions/find_or_install.sh
- src/extensions/caf-foot
- src/extensions/cafrun-head
- src/make.inc
- src/make.inc.Cray-XE
- src/tests/integration/coarrayHelloWorld/Makefile
- src/tests/integration/pde_solvers/coarrayBurgers/Makefile.inst
- src/tests/integration/pde_solvers/coarrayBurgers/run.sh
- src/tests/integration/pde_solvers/coarrayBurgers/scripts/run.sh
- src/tests/integration/pde_solvers/coarrayBurgers/scripts/run_troubleshooting.sh
- src/tests/integration/pde_solvers/coarrayHeatSimplified/Makefile
- src/tests/integration/pde_solvers/navier-stokes/Makefile
- src/tests/performance/BurgersMPI/Makefile
- src/tests/unit/extensions/CMakeLists.txt
- windows-install.sh
[links]:#
- Change `mpirun` to `mpiexec` and `mpif90` to `mpifort` in accordance with best practices as outlined in MPI standard.
- Fixed bug and style issues in HPC Linux install script
Better …
> Issue 378 mpi names

- src/mpi/mpi_caf.c
[links]:#
policies on:
- Pull request (PR) naming to indicate work in progress (WIP),
and to attach the PR to …
> Enforce MPI progress during event_wait

- .gitattributes
- src/make.inc
- src/openshmem/Makefile
- src/openshmem/openshmem_caf.c
[links]:#
- Increasing test coverage for all bug-fix …
> Experimental OpenSHMEM version

- CMakeLists.txt
- src/mpi/CMakeLists.txt
[links]:#
Install opencoarrays.mod again
Forgot to add logic to install in last refactor/PR
- Increasing test …
> Issue 268 improve wrappers

- src/mpi/CMakeLists.txt
Thanks to @ascmplx for pointing this out. Fixes #452
[links]:#
Install `opencoarrays.mod` not `opencaorrays.mod`
Fix transposition typo
- Increasing test coverage for …
> Fix typo for mod file install destination

- src/tests/integration/pde_solvers/CMakeLists.txt
[links]:#
Eliminated addition of the Navier-Stokes solver subdirectory in the corresponding CMake script.
Navier-Stokes solver build fails inside a Lubuntu 17.10 Linux virtual machine when build …
> Eliminate Navier-Stokes solver build

- .Dockerfiles/master-jupyter-inherit/.dockerignore
- .Dockerfiles/master-jupyter-inherit/Dockerfile
- .Dockerfiles/master-jupyter-inherit/Makefile
- .Dockerfiles/master-jupyter-inherit/hooks/build
- .gitattributes
[links]:#
Automated docker build for creating jupyter-CAF-kernel binder instances from latest master branch
Allow nightly update of binder kernel so that users can test bugs in the cloud against …
> Dockerfile to in cloud with jupyter-CAF-kernel

- CMakeLists.txt
- cmake/makeDist.cmake
- cmake/opencoarrays-VER-SHA256.txt.asc.in
- cmake/opencoarrays-VER-SHA256.txt.in
[links]:#
Add a `dist` target using CMake
Make it easier for project maintainers to create release tarballs, and SHA256 checksums and GPG signatures, if possible. This will make it easier for other …
> Issue 413 make dist

- src/extensions/cafrun.in
[links]:#
See issue title.
This  one is obvious. …
> Fix typo in cafrun.in: ehco -> echo

- .travis.yml
(I hope)
[links]:#
Travis-CI updated their environment and as a result brew install gcc broke
So the CI system works again
- Increasing test coverage for all …
> Fix "brew install gcc" failures on Travis macOS

- .travis.yml
[links]:#
Trivial change: ensure CMake gets built for install script installs
Remove unintentionally
- …
> Make sure CMake is still built by install script.

- src/mpi/mpi_caf.c
[links]:#
This bug fix enables multithreaded execution via OpenMP.  It was developed by @afanfa whom I'm asking to review and advise us on whether it is ok to merge this branch into master.  Are …
> Merge bugfix-multithread into master

- INSTALL
- INSTALL.md
- install.sh-usage
- prerequisites/build-functions/download_if_necessary.sh
- prerequisites/build-functions/set_or_print_default_version.sh
- prerequisites/build-functions/set_or_print_url.sh
- prerequisites/install-functions/build_opencoarrays.sh
[links]:#
Fixes to install scripts and updated installation instructions
GCC/GFortran devs didn't have the patience to read the entire INSTALL.md
- Increasing test …
> Issue 478 update documentation

- .travis.yml
- CMakeLists.txt
- INSTALL.md
- developer-scripts/travis/before_install.all.sh
- developer-scripts/travis/before_install.linux.sh
- developer-scripts/travis/before_install.osx.sh
- developer-scripts/travis/install.linux.sh
- developer-scripts/travis/install.osx.sh
- developer-scripts/travis/test-script.InstallScript.sh
- developer-scripts/travis/test-script.cmake.sh
- src/extensions/caf.in
- src/extensions/cafrun.in
[links]:#
Numerous changes including:
- Use only two macOS Travis-CI images to expedite wait time
- Port nearly all shell code in `.travis.yml` to scripts in `developer-scripts/travis`, simplifying …
> Travis and install fixes

- install.sh-usage
[links]:#
Improve installer documentation.
Warn about a limitation of `./install.sh -B`.
- Increasing test …
> Document that -B only works for arg gcc

- developer-scripts/gcc-trunk-install.sh
[links]:#
Edit and rename the developer-scripts/patched-trunk-install.sh script to build the GCC trunk without patching it.
This  captures the workflow for using install.sh to build OpenCoarrays a …
> Add patched-trunk install script option: unpatched build

- CMakeLists.txt
- src/CMakeLists.txt
- src/mpi/CMakeLists.txt
- src/tests/regression/reported/CMakeLists.txt
- src/tests/regression/reported/issue-488-multi-dim-cobounds.f90
@neok-m4700 provided the patch and these tests, which I, @zbeekman,
have modified and integrated with the OpenCoarrays build & test system.
Various changes were made to improve the generality of the build/test infra.
Moving forwards, use this example to add tests, but you can ignore changes
in src/mpi/CMakeLists.txt, src/CMakeLists.txt and all changes besides
L771-772 in the top level CMakeLists.txt
[links]:#
[coverage]: https://img.shields.io/codecov/c/github/sourceryinstitute/OpenCoarrays/master.svg?style=f …
> Add anti-regression tests submitted \w issue #488

- CMakeLists.txt
- src/tests/regression/open/issue-422-send.f90
- src/tests/unit/send-get/CMakeLists.txt
- src/tests/unit/send-get/alloc_comp_multidim_shape.F90
[links]:#
This pull request adds a unit test that exposes issue #511. 
All previous tests were passing with GCC 6.4 and 7.3 despite issue #511 so we needed a test to highlight the issue.
I was …
> Issue 511 unit test

- FAQ.md
[links]:#
Added a FAQ
Adhere to DRY, improve documentation
- Increasing test coverage for all bug-fix PRs for …
> Add FAQ.md frequently asked questions file.

- src/mpi/mpi_caf.c
[links]:#
Single PR translating tabs to spaces.
Consistency. Git workflow. Please consider using either tabs or spaces but not both.
- Increasing test coverage for all …
> tabs > spaces

- prerequisites/build-functions/build_and_install.sh
- prerequisites/build-functions/patches/gcc/8.1.0/partially-revert-rev259385.diff
- prerequisites/build.sh
[links]:#
Edited installer to detect when it is building GCC 8.1.0 and, if so, to patch the gfortran source.
A GCC commit introduced just before the release of 8.1.0 caused regressions in …
> install.sh patches gfortran 8.1.0 before building

- src/iso-fortran-binding/ISO_Fortran_binding.c
- src/iso-fortran-binding/ISO_Fortran_binding.h
- src/tests/unit/iso-fortran-binding/ISO_Fortran_binding_tests.c
…d committee about the proposed changes to the standard.
[links]:#
Removed CFI_FAILURE and redifined CFI_SUCCESS as 0. Changed the tests and implementation of CFI_is_contiguous as a result. …
> Fixed CFI_SUCCESS and eliminated CFI_FAILURE after asking Bill Long.

- src/tests/integration/pde_solvers/coarrayHeatSimplified/main.f90
[links]:#
Updated the main program in the co_heat test.
Due to an overly fine grid and an explicit time step, the co_heat
test was previously unstable.  Furthermore, due to a lax test,
previously …
> Make co_heat test numerically stable & stricter

- src/extensions/caf.in
[links]:#
Updated copyright date sin `caf.in`.
`caf --version` was printing a the date range 2015-2016
- …
> Update caf.in copyright dates

- install.sh
- install.sh-usage
- prerequisites/acceptable_compiler.f90
- prerequisites/build-functions/set_or_print_default_version.sh
- prerequisites/build-functions/set_or_print_installation_path.sh
- prerequisites/build.sh-usage
- prerequisites/install-functions/build_opencoarrays.sh
- prerequisites/install-functions/find_or_install.sh
- prerequisites/install-functions/print_header.sh
[links]:#
1. Set the installer's default/minimum GCC version to 8.2.0.
2. Added a `--prefix-root` (alternatively `-r`) flag to the installer.
See issue #591 
- …
> Fix #591 installer updates

- .VERSION
- README.md
Bumping version file and cleaning up issues in README.md
> Fix release

- prerequisites/build-functions/set_or_print_url.sh
- Fixes #606
[links]:#
Fix GCC head URL. I think I authored this in c56e6cdfdc683f508c3124f4c07db8bbcea115ac, even though the blame shows Damian. Perhaps we were working together in person or something.
Breaks installation
does not already exist a …
> Fix GCC head url

- prerequisites/install-functions/build_opencoarrays.sh
- prerequisites/install-functions/report_results.sh
- Fix #607
- Fix #584
[links]:#
Fix quoting inside `set var ("thing" $var)` 🤞 
Setup.csh was not generating correct csh code.
- Increasing test coverage for all …
> Fix csh/tcsh `set` calls in `setup.csh`

- README.md
[links]:#
Updated links in the README.md.
Fortran 2018 has now been published and the final pre-publication committee draft is available online.  The corresponding link has been updated and some …
> Update/prune links in README.md

- README.md
[links]:#
Fix a broken link in README.md.
does …
> Update article citation link in README.md

- prerequisites/install-functions/find_or_install.sh
[links]:#
Edited `prerequisites/install-functions/find_or_install.sh`
`install.sh` was mistakenly using MPICH's version number
where it should have used GCC's version number
This pull request (PR) …
> Fix installer's minimum-version check for gcc

- .VERSION
[links]:#
Updated `.VERSION` file to reflect latest version (tag) number.
`.VERSION` wasn't updated in the most recent release.
- Increasing test coverage for all …
> Bump fallback version number

- .github/ISSUE_TEMPLATE/reproducible-bug-report.md
[ci skip]
[links]:#
Fixed markdown link typo
Properly linkify info about fenced code blocks
be introduced)
[links]: #
[best practices]: https://tbaggery.com/2008/04/19/a-note-about-git-commit-messages.html
[commit messages]: https://thoughtbot.com/blog/5-useful-tips-for-a-better-commit-message
[Pull Requests]: …
> Fix typo in issue template link

- .github/PULL_REQUEST_TEMPLATE.md
- .github/stale.yml
[ci-skip]
[links]:#
Add additional labels for stalebot to ignore
Stalebot is only kinda-useful for prodding us, and should respect the logic we want so it's not constantly hounding us and others.
be introduced)
[links]: #
[best practices]: https://tbaggery.com/2008/04/19/a-note-about-git-commit-messages.html
[commit messages]: …
> Update stalebot settings to match our labels

- CMakeLists.txt
- cmake/InstallFileManifest.cmake
[links]:#
Generate and install a receipt with SHA256 checksums of all installed assets
Help towards finishing #89; now the software can know how to cleanup after itself. Also, this will help debug reproducible builds, and will help users verify their builds match any official distributions.
- I will wait at least 24 hours before …
> Install receipt

- prerequisites/build-functions/build_and_install.sh
[links]:#
Added warning output in when running the installer to build GCC on macOS Mojave or later.
XCode doesn't install required headers by default so users need to know how to install them if they haven't already.
OpenCoarrays developer a chance to …
> Fix #682 macOS Mojave warning

- .github/FUNDING.yml
- Fixes #695
[links]:#
- I have not introduced errant white space (no trailing white space or white space errors may
be introduced)
- I …
> Chore: Fix FUNDING.yml

- install.sh
- install.sh-usage
- prerequisites/build-functions/download_if_necessary.sh
- prerequisites/build-functions/set_or_print_default_version.sh
- prerequisites/build-functions/set_or_print_downloader.sh
- prerequisites/build-functions/set_or_print_url.sh
- prerequisites/build-functions/unpack_if_necessary.sh
- prerequisites/build.sh
[links]:#
Replaced all uses of `svn` with `git` in the installer.
GCC has converted from using a subversion repository to using a `git` repository.  With this PR,  
```
./install.sh -p gcc -b master
```
now replaces the following:
```
./install.sh -p gcc -b trunk
```
because the latter command now accesses an old copy of GCC frozen at the last subversion commit before GCC stopped supporting subversion.
This pull …
> git clone gcc branches (remove all use of svn)

- .VERSION
- prerequisites/install-functions/report_results.sh
[links]:#
Bumped the version number from 2.8.0 to 2.9.0 & updated README.md.
This is a release candidate.
- I have not introduced errant white space (no trailing white space or white space …
> Tag, bump version, & update README.md

- .github/workflows/ci.yml
[links]:#
Create a CI script for GitHub
I was told that Travis CI was no longer working, and there's no reason to continue using it if GitHub has their own service built in.
- I have not …
> Switch ci to GitHub

- prerequisites/build-functions/set_or_print_default_version.sh
[links]:#
Update default GCC version to 12.2.0 in the installer.
Requested in issue #765 
- I have not introduced errant white space (no trailing white space or white space errors may
be …
> Update default GCC version to 12.1.0
