.travis.yml, CMakeLists.txt, README.md, STATUS.md, src/tests/integration/CMakeLists.txt, src/tests/integration/pde_solvers/coarrayBurgers/CMakeLists.txt, src/tests/integration/pde_solvers/navier-stokes/CMakeLists.txt, src/tests/performance/BurgersMPI/CMakeLists.txt
- Fixes #28 : When CMake release types are passed to CMake, optimization flags are added to the gfortran compiler, which trigger bugs in GCC for GFortran < 5.4
- Fixes #31 : Generate files at CMake config time in the binary tree not the source tree. Also don't delete them with `make clean`
- Fixes #56 : A number of bad links existed in the README.md
Normally, once we're on the Github Flow workflow, some of these may have deserved their own branch (i.e., issue-28-gcc-flag-bug, issue-31-make-clean, issue-56-bad-links but in the interest of time and paying down technical debt, I have applied all of these on the same branch, in the same PR.)
=> Issue 28 opt flag fix

CMakeLists.txt, src/tests/unit/extensions/CMakeLists.txt
Brings branch 1.x closer to master, and applies, at least IMO, clearer CMake version checking logic.
=> Apply clearer CMake version checking from master

doc/dependency_tree/gitkeep.sh, install.sh, src/tests/integration/pde_solvers/coarrayBurgers/run.sh
- Cherry picking etc. earlier caused either the re-introduction of
white space errors, or these files escaped correction during the
first cleanup.
=> Fix whitespace errors

src/mpi/mpi_caf.c
- Whitespace changes introduce noise and difficulties
dealing with diffs and version control systems
- Even in fixing them, these whitespace errors can be
insidious
- A carefully crafted whitespace cleanup commit was replayed
ontop of changes from @afanfa, and resulted in an accidental
reversion of his changes. This commit fixes that.
=> Undo accidental revert from c4caefaf

install.sh
Use the gcc and g++ that is installed in /usr/bin by XCode with its Command-Line Tools.
=> Enable install.sh to build CMake on OS X by using Apple LLVM

install.sh, install_prerequisites/build, install_prerequisites/set_SUDO.sh
This commit eliminates the need for global "sudo ./install.sh" or "sudo ./build" when installing to a path that requires sudo privileges.  Now the need for sudo is detected during the execution of "install.sh" or "build" and the subsequent use of sudo is localized to the places where it is needed (e.g., "sudo make install" or "sudo mv setup.sh $install_path".
=> Eliminated need for sudo install.sh or sudo build

.gitattributes, developer-scripts/git-hooks/applypatch-msg.sample, developer-scripts/git-hooks/commit-msg, developer-scripts/git-hooks/post-update.sample, developer-scripts/git-hooks/pre-applypatch.sample, developer-scripts/git-hooks/pre-commit, developer-scripts/git-hooks/pre-push, developer-scripts/git-hooks/pre-rebase.sample, developer-scripts/git-hooks/prepare-commit-msg.sample, developer-scripts/git-hooks/update.sample, developer-scripts/setup-git.sh
- pre-commit hook to check for white-space errors
- commit-msg hook to ensure commit messages are properly formatted
- Commit messages should start with a capitalized imperative verb "do, fix, enable" and a brief summary, less than 50 characters long of what the commit is about
- If multiple lines, the second line should be left blank.
- subsequent lines should not be more than 72 characters long
- setup line endings and white space
For more info on writing good commit messages please see:
1. https://robots.thoughtbot.com/5-useful-tips-for-a-better-commit-message
2. http://tbaggery.com/2008/04/19/a-note-about-git-commit-messages.html
3. https://www.reviewboard.org/docs/codebase/dev/git/clean-commits/
The 50 character limit may seem arbitrary, but it is important for how Github.com shows …
=> Add script to change git settings and use hooks

CMakeLists.txt
Both ./install.sh --version and caf --version output the VERSION argument from "project" statement in the top-level CMakeLIsts.txt file. Immediately before this commit, git clones show a number that matches the most recent release even though new commits have happened. This commit bumps the VERSION from 1.2.2 to 1.2.3-prerelease to distinguish the current development version from the most recent release and the upcoming release.
=> Bump version # to 1.2.3

CMakeLists.txt
PR #92 accidentally merged `devel` into the working branch before merging back into master. This PR was reverted via PR #95 and the intended changes are now being replayed on top of master, without the unintended merge of `devel` into `master`.
=> replay changes to silence inconsequential errors from bad PR #92

install.sh, install_prerequisites/stack.sh
The stack_new function invoked by install.sh outputs inconsequential
errors on OS X because of the lack of support for the -g flag in bash
"eval".  This commit pipes that output to /dev/null.
(cherry picked from commit 5491f66ea81e2ca24d42abd78f65d4e4e92b7eed)
I thought I had already fixed things, but apparently merge commits are more complicated than I fully understand. This *should* bring `master` back to where we want it. I'm poking around a little bit more to see if that is indeed the case.
=> Eliminate inconsequation install error messages.

install.sh, install_prerequisites/build
The "build" script now detects a missing download mechanism (as designated in the $fetch variable) and prompts the user to download the relevant tar ball and restart the installation.  A few exit statements have also been updated to have unique exit codes. A minor edit in "install.sh" indicates to the user that the tar ball will be downloaded "if necessary", i.e., if it isn't already found in the expected location.
This has only been tested when fetch=wget.  It should be able to detect if another missing required download mechanism (e.g., svn or ftp) is missing, but it's possible the printed messages will be less clear in that case.
=> Handle missing wget gracefully.

doc/dependency_tree/opencoarrays-tree.txt, install.sh, install_prerequisites/acceptable_compiler.f90, install_prerequisites/build, install_prerequisites/check_version.sh
Also bumping the minimum gfortran version to 5.3.0 and setting the default, script-installed gfortran so that it downloads the current 5 branch instead of the current trunk (6.0.0).
=> Add m4 to dependency tree

install_prerequisites/build
This fixes a regression that broke the "build" script for non-default releases
of prerequisites (e.g., "./build gcc 5.2.0") and the build of unspecified versions
(e.g., "build gcc").  The regression had no impact on invocations inside install.sh
(which are all of the form "./build gcc --default ...") and no impact on builds of
the trunk development branch (e.g., "./build gcc trunk") and these remain working.
Now "build" works for all available released versions of all packages and for
the "trunk" development branch of gcc.  Building non-trunk development branches
(e.g., gcc-5-branch) remains broken by the same regression. Enabling the build
of  non-trunk development branches will wait until the use of POSIX getopts
argument parsing has been implemented.
=> Fixed nondefault- & unspecified-release builds.

.travis.yml
Missing from this PR, i.e., still under development:
- Clever managing which dependencies are pre-loaded through more expedient Travis-CI logic, when build scripts have not been touched, but building as much as we can when modified in the commit range being tested by Travis-CI
- Testing car wrapper scripts after OpenCoarrays has been installed (This isn't done in any tests yet)
Additionally, `.travis.yml` is getting unwieldy and could benefit from being broken up into one or more shell scripts ( #101 )
=> Expand test matrix to include install.sh script and `build`

AUTHORS.md, CAF_ABI.md, CONTRIBUTING.md, GETTING_STARTED.md, INSTALL.md, LICENSE, README.md, STATUS.md
- Major cleanup to documentation
- CAF_ABI.md needs further attention, esp. TODO lists
- Added a proper CONTRIBUTING.md
- Still need to add:
- Developer guide for SI devs
- CHANGELOG.md
Fixes #107
=> Fix links, typos & formatting in markdown docs

CMakeLists.txt, src/libcaf.h, src/mpi/mpi_caf.c, src/tests/unit/sync/CMakeLists.txt, src/tests/unit/sync/duplicate_syncimages.f90
The list of images passed to sync images cannot contain duplicates. This patch checks this condition.
Test case included.
=> Duplicates in sync images array

.gitattributes, .gitmodules, developer-scripts/git-hooks/commit-msg, developer-scripts/git-hooks/pre-commit, developer-scripts/setup-git.sh
See #119 as well.
I have updated the git setup/config scripts to help ease working with
submodules. I suggest re-running the git setup developer script.
Submodules are a somewhat complicated beast, but I really think for our usage,
pulling in OFP via submodule sounds like the best route. If we change our minds
once we start hacking with OFP, we'll be able to investigate other alternative
integration strategies. (Subtree merge, committing code directly, scripted external
dependency, etc.)
To begin reading up: https://git-scm.com/book/en/v2/Git-Tools-Submodules
=> Add OFP as a git submodule

.gitattributes, .gitmodules, developer-scripts/setup-git.sh
- Put OFP into vendor subdir -- conventional SCM practice
- Make sure we don't archive git stuff
- Update git settings/setup script for submodule help
Git submodule may be unnecessary, OFP appears to need some cleanup and install/build system love
=> Add OFP as git submodule connected to #119

.gitattributes, .gitmodules, developer-scripts/setup-git.sh
Reverts sourceryinstitute/opencoarrays#129
- The wrong git submodule was added. Should have been OpenFortranProject/ofp-sdf
- We will consume OFP as an external dependency, so don't need to sub-module it
=> Revert "Add OFP as git submodule connected to #119"

install.sh, install_prerequisites/build
This fixes #123 and improves the setup.sh file that install.sh creates.  When install.sh builds prerequisites from source, "source setup.sh" sets LD_LIBRARY_PATH correctly for both 32- and 64-bit builds on Linux and OS X and it adds gfortran/gcc/g++ to PATH and correctly detects when to add m4 to the PATH.
=> Fix issue #123 build ftp fails on linux

COPYRIGHT-BSD3, doc/dependency_tree/gitkeep.sh, install_prerequisites/acceptable_compiler.f90, install_prerequisites/build, src/extensions/caf-foot, src/extensions/caf-head, src/extensions/cafrun-foot, src/extensions/cafrun-head, src/extensions/opencoarrays.F90, src/libcaf-gfortran-descriptor.h, src/libcaf.h, src/mpi/mpi_caf.c, src/tests/performance/psnap/timemeasure.c, src/tests/unit/collectives/co_broadcast.F90, src/tests/unit/collectives/co_max.F90, src/tests/unit/collectives/co_min.F90, src/tests/unit/collectives/co_reduce.F90, src/tests/unit/collectives/co_sum.F90
Fixes #130
Find files with `2015` and have been modified since December 31, 2015:
```
git grep --name-only 2015 $(git log --pretty=format:%H --since="12/31/2015") | \
cut -d : -f 2 | sort | uniq | \
while read line; do \
grep -Hn 2015 $line; \
done > 2015-refs.ack
```
Then open `2015-refs.ack` in Emacs and `M-x compilation-mode` to jump to the file and line easily
=> Update copyright year for files touched in 2016

install.sh
Previously install.sh echoed "y" when a user input "n" and vice versa.  This pull request flips this behavior and makes affirmative answers ("Y") the default as requested by Clune and Filippone.
=> Correct flipped y/n reporting and make Y default.

3rd-party-tools/open-fortran-parser-sdf/trans/CMakeLists.txt, 3rd-party-tools/open-fortran-parser-sdf/trans/Makefile, 3rd-party-tools/open-fortran-parser-sdf/trans/caf-lower.str, 3rd-party-tools/open-fortran-parser-sdf/trans/fast-to-ocaf.str, 3rd-party-tools/open-fortran-parser-sdf/trans/testfile.f90, CMakeLists.txt, install_prerequisites/build-ofp.sh, src/extensions/caf2ocaf-foot.sh, src/extensions/caf2ocaf-head.sh, src/mpi/CMakeLists.txt, src/tests/source-transformation/co_sum.f90, src/tests/source-transformation/derivative.f90, src/tests/source-transformation/transformed-co_sum.f90, src/tests/source-transformation/transformed-derivative.f90
This will supersede #137, but in terms of the changes applied to the codebase it is *the same*. Here is a list of the changes/transformations I made: :tophat: :sparkles: :rabbit2:
- :octocat: Rebase `add-fop` branch onto `devel` (was based on `master`)
- :memo: Re-word commits to follow the guidelines [here](http://tbaggery.com/2008/04/19/a-note-about-git-commit-messages.html) and [here](https://robots.thoughtbot.com/5-useful-tips-for-a-better-commit-message)
- :x: Drop meaningless/useless/virtually-empty commits
- :bug: Fixup/squash commits that were clearly fixing errors from previous commits (make it look like errors were never introduced, or items were never forgotten in individual commits)
- ~~Add fallback location to find OFP_HOME if user forgets to pass this... probably not super …
=> :bath: Cleanup add-ofp branch

CMakeLists.txt, install.sh
- Ensure that CheckFortranSourceCompiles can compile test/introspection code which is in F90 not f77
- Make sure `install.sh` returns proper exit code... A bunch of the other scripts need to be examined for this defect too....
=> Fix small CMake introspection issue

install.sh, install.sh-usage, prerequisites/build-functions/download_if_necessary.sh, prerequisites/build-functions/set_or_print_default_version.sh, prerequisites/build-functions/set_or_print_downloader.sh, prerequisites/build-functions/set_or_print_url.sh, prerequisites/build.sh, prerequisites/build.sh-usage
The following now works to list the available gcc development branches:
```
./install.sh -B gcc
```
and the following will build, for example, the gcc trunk:
```
./install.sh -b trunk -p gcc -i /opt
```
=> Support gcc dev branch builds

prerequisites/build-functions/set_or_print_downloader.sh, prerequisites/build.sh, prerequisites/install-ofp.sh
=> Use any of ftp wget curl

src/extensions/caf-foot, src/mpi/CMakeLists.txt
=> caf invokes compiler specified by OC-build-time FC

.travis.yml
If I'm half a clever as I think I am 😋 this should fix broken builds due to GCC upgrades on OS X and let us test GCC 6.1.0 across all OSes.
Note, I have yet to build a bottle for MPICH that uses gcc as the C compiler, so on OS X, clang will be used to compile the OpenCoarrays library, until I can build a bottle... See #65
=> Update Travis-CI to use GCC-6

.travis.yml, install.sh, install.sh-usage, prerequisites/build-functions/set_or_print_installation_path.sh, prerequisites/build.sh
previously subdirectories named after the package and version were
appended to user-specified install prefixes so
./install.sh -p gcc -i /opt -I 6.1.0
would produce an installation directory named "/opt/gcc/6.1.0".
This differs from how most packages interpret the install prefix
and can result in redundancy if the user has already included such
information in the -i argument. With this commmit, the bare user-
-specified install prefix will be used with nothing appended.  If
no -i argument is present, the default still contains the package
name and version: ${OPENCOARRAYS_SRC_DIR}/prerequisites/installations/gcc/6.1.0)
=> Treat user-specified install prefix as full path

install.sh
This change was already made for installation of other packages.
Now
./install.sh --install-prefix /foo/bar/
will result in the installation of OpenCoarrays to /foo/bar without
appending "opencoarrays/<version-number>" to the installation path.
=> Enable bare install-prefix for OpenCoarrays itself

install.sh-usage, prerequisites/build.sh, prerequisites/build.sh-usage
It appears the problem was a mismatch between an argument name in
install.sh-usage (--branch) and the corresponding argument in
prerequisites/build.sh (--install-branch).
=> Fixes #216

install.sh-usage, prerequisites/acceptable_compiler.f90, prerequisites/install-functions/find_or_install.sh, src/libcaf.h, src/mpi/mpi_caf.c, src/tests/unit/send-get/get_with_offset_1d.f90
* Fixes to support gcc-7's caf-interface.
* Added preproccessor guards.
* First steps to implemeting full featured caf_get_by_ref().
WARNING! Errorneous at the moment.
* Reverted change for burgers test in CMakeLists.txt.
Fixed most issues. One still needs a patch to gfortran. Therefore
the pde-solver might fail with an unpatched gfortran still.
* Removed define sticking to gcc-7.
* Fixed typo.
* Send-get/get_with_offset_1d.f90: Needs sync all at the end of the main program
or the scope where array descriptors are stored may be already
destroyed when accessed by other (slower) images.
mpi_caf.c: Fixing sync_images, when a stopped image is slow to reach its
caf_finalize and set the stopped status, while other images have read an
ok status already and now wait on its send. Realized by using …
=> Fix for sync images issue and some cleanup (#222)

prerequisites/install-functions/find_or_install.sh
The installation no longer fails when a GCC installation is in the
PATH and is too old to support the Fortran 2003 compiler_version
function invocation in prerequisites/acceptable_compiler.f90.
=> Fixes #229

LICENSE
Fixes #233 
Now github should detect this as a BSD 3-Clause license with 100% accuracy, although we may have to go through the source code file headers and fix all of those too. Here is how github determines the licensing: https://github.com/blog/1964-open-source-license-usage-on-github-com
=> License detection

src/extensions/opencoarrays.F90, src/mpi/CMakeLists.txt
Fixes #204
At configure time, choose whether to expose the `caf_init` and
`caf_finalize` functions in the opencoarrays (extension) module by using `-DCAF_EXPOSE_INIT_FINALIZE`.
N.B. the semantics of using C pointers with Fortran still mystifies me a bit, and I don't really understand what the point of passing `argc` and `argv` to `MPI_init` is (since I always use fortran, where the only arg is `ierr`). So for my interface to `caf_init` which takes `argc` and `argv` as arguments, I have declared both as `type(c_ptr)` so it is the users responsibility to pass the appropriate `c_ptr` in to them. In my testing I just passed `c_null_ptr`s and it seemed to work fine. Also, please note, that the `caf` compiler wrapper script does not pass in the installed module file for open coarrays aware …
=> Expose caf_init and caf_finalize in module to allow use with f2py, see #204

src/mpi/mpi_caf.c
This PR is to supersede #237 if that's OK with @vehre and everyone else.
=> Fixed int128t issue. Hopefully.

.travis.yml, CMakeLists.txt, src/mpi/CMakeLists.txt
This (#39), along with #79 are blocking #22.
Now through the magic of `find_package(MPI)` one need not pass in the MPI compiler wrapper to CC and FC, but simply passing FC=gfortran, CC=gcc-6 should do the trick.
=> Better cmake mpi passing #39

.travis.yml, CMakeLists.txt
Addresses issue reported by @rouson [here](https://github.com/sourceryinstitute/opencoarrays/pull/253#issuecomment-262607188) and makes it so that CMake can find MPI installation from `install.sh` even when it's not on the user's `PATH`
=> Fix mpi search

CMakeLists.txt, src/extensions/opencoarrays.F90, src/mpi/CMakeLists.txt, src/tests/integration/dist_transpose/coarray_distributed_transpose.F90, src/tests/integration/pde_solvers/navier-stokes/coarray-shear_coll.F90, src/tests/performance/BurgersMPI/shared.F90, src/tests/performance/mpi_dist_transpose/mpi_distributed_transpose.F90, src/tests/unit/init_register/CMakeLists.txt, src/tests/unit/init_register/initialize_mpi.F90
Untested, but this *should* behave better than the previous
implementation and should try really hard to "do what you mean" ™️ 
I'll also try to address #246 as best we can... just do it through checking the .mod file compatibility... readelf is not something I want to deal with, and strings -a doesn't work because everyone uses strip before shipping binaries.
@jerryd mentioned that you might be able to unzip .mod files and get the GFortran version, but I haven't been able to do this, despite a few tries.
=> More robust MPI handling/finding

INSTALL.md
Currently, the link in the TOC at the top of INSTALL.md is https://github.com/sourceryinstitute/opencoarrays/blob/master/prerequisites. It should be https://github.com/sourceryinstitute/opencoarrays/blob/master/INSTALL.md#prerequisites.
=> Prerequisites link broken in INSTALL.md

src/extensions/caf-foot, src/extensions/cafrun-foot, src/mpi/CMakeLists.txt
Before this commit, the `caf` was invoking gfortran directly because of the new practice of passing compilers instead of MPI wrappers in`FC=gfortran cmake ..` and `cafrun` was hardwired to invoke `mpif90`. With this commit, `caf` invokes `${MPI_Fortran_COMPILER}` and `cafrun` invokes `${MPIEXEC}`.
=> Edit caf/cafrun for FC=gfortran instead of mpif90

.travis.yml, CMakeLists.txt
See discussion at #281 for details on the CTest timeout.
Attempting to decrease verbosity of the `matrix.include` element for `.travis.yml` using YAML anchors, references and merges.
=> Add safer timeout for GCC 7 test and compact .travis.yml

src/extensions/cafrun-foot
Fixes small issue I accidentally introduced in https://github.com/sourceryinstitute/opencoarrays/commit/878e5b488cee1feb2186480717871c00e51a3a90 that causes `cafrun --help` to fail. Sorry!
=> Fix typo preventing cafrun --help from working

CMakeLists.txt
The former version was including CheckCSourceCompiles instead of the Fortran
version.  This in principle does not matter, because CheckFortranSourceCompile
is included already.  For clarity nevertheless this should be made consistent.
=> Include CheckFortranSourceCompiles where it is needed.

prerequisites/install-functions/find_or_install.sh
There was a typo in the check for the compiled fortran binary that made the check fail every time.
=> fix gfortran compiler detection (issue 305)

src/mpi/mpi_caf.c
Take the source index of the image that is sending the current image data from
the MPI_status handle of Waitany instead of the index i, which only denotes the
handle in the array of receive-requests.
Fixes #302
=> Fix sync images to take the syncer's id from mpi_status.

README.md, STATUS.md
But don't forget about it... in 2018 it will turn red without update
[ci skip]
=> Move "maintained?" badge to STATUS.md

prerequisites/build-functions/edit_GCC_download_prereqs_file_if_necessary.sh, prerequisites/build-functions/set_or_print_url.sh
is addressing
touches
touches
changes
set of changes
commit resolves an open issue.
Add logic to the edit_GCC_download_prereqs_file_if_necessary.sh script to …
=> Only edit gcc6 or older download_prerequisites

CMakeLists.txt, prerequisites/install-functions/build_opencoarrays.sh
Fixes #359
Hunt for `mpiexec` or `mpirun` in the same directory that `MPICC` and `MPIFC` are in when building with `install.sh` and then pass `-DMPIEXEC=...` to CMake so that the proper runtime environment is used...
In some cases mpiexec was getting pulled in from the user's `PATH` and differed from the MPI implementation selected by the build script. This caused incompatibilities since `mpiexec`/`mpirun` from a different MPI implementation than the one used to compile was  being used.
`DO NOT MERGE:` to the beginning of …
=> Ensure the correct MPIEXEC is used

CMakeLists.txt
Search for `noexecstack` in `MPI_<lang>_LINK_FLAGS` and if found issue a warning and overwrite with `execstack` due to #317
`-Wl,-z,noexecstack` seems to cause segfaults in the GFortran runtime, e.g., when internal `contains` procedures are used.
For additional details see:
- #317
- https://gcc.gnu.org/bugzilla/show_bug.cgi?id=71729#c1
- https://github.com/sourceryinstitute/OpenCoarrays/issues/172#issuecomment-271582653
#317 is triggered on Fedora 25
Fixes #317
`issue-<#>` …
=> Check for and remove `noexecstack` added by MPI

CMakeLists.txt, prerequisites/install-functions/build_opencoarrays.sh
This edit implements the suggestion in the first comment
of CMake issue 16804 posted at
https://gitlab.kitware.com/cmake/cmake/issues/16804
Corrected typo in CMakeLists.txt
See the first comment in [CMake issue 16804](https://gitlab.kitware.com/cmake/cmake/issues/16804).
is addressing
touches
set of changes
clicking the "details" link to the right of the …
=> Fix typo in top-level CMakeLists.txt

prerequisites/build-functions/build_and_install.sh
Small bug fix to make a66121a9b576044ee070cd178a8a7f40837f1c0c and 3947bdb1e6fe6abffa23868121ece9fb9055e206 work together correctly. 3947bdb1e6fe6abffa23868121ece9fb9055e206 had a non-portable sed usage and a66121a9b576044ee070cd178a8a7f40837f1c0c caused the patch to not actually get applied.
=> Fix application of patch for MPICH 3.2

src/mpi/mpi_caf.c
[links]:#
Replaced calls to non-existent error_stop function (don't mix this up with PREFIX (error_stop)) with the internal_terminate.
Allow compiling again.
policies …
=> Fix by replacing error_stop with terminate_internal.

install.sh-usage, prerequisites/install-functions/find_or_install.sh
[links]:#
Added conditional block in `find_or_install.sh` to check for and use the user-specified `cmake` before checking for the default `cmake` or a `cmake` in the `PATH`.
See #404 
Why did you …
=> Fix #404 -m/--with-cmake overrides default cmake

prerequisites/build-functions/set_or_print_url.sh, prerequisites/install-functions/download-all-prerequisites.sh
- More portable (Gzip more common than bzip2)
- No .bz2 files are present for 6.4 on GNU FTP server
- Fixes #408
[links]:#
Downloading GCC releases with install.sh now tries to fetch the more …
=> Switch GCC url tail `.bz2` ==> `.gz`

install.sh, install.sh-usage, prerequisites/build-functions/build_and_install.sh, prerequisites/build.sh, prerequisites/build.sh-usage
[links]:#
The `install.sh` and `build.sh` now recognize the `-z` or equivalently `--disable-bootstrap` options and add or omit the corresponding arguments during `make` of GCC.
When building with a …
=> Add install.sh/build.sh option --disable-bootstrap

INSTALL.md
Documentation fix: update INSTALL.md based on Issue #395 
The user who added FreeBSD installation support suggested these documentation changes.
policies on:
- Pull request (PR) naming to indicate work in progress (WIP),
and to attach the PR to the appropriate bug report, or feature
request [issue]
- White space (no trailing white space or white space errors may
be introduced)
- Commenting code where it is non-obvious and non-trivial
- Running tests locally, to ensure all of them pass
- Maintaining or increasing test coverage
- Logically atomic, self …
=> Update INSTALL.md FreeBSD info to fix #395

install.sh, prerequisites/install-functions/install-xcode-clt.sh
On macOS, add logic to install script that will install Xcode command
line tools. Most logic cribbed from Homebrew installer.
Fixes #325
[links]:#
If on macOS and using `install.sh`, determine if …
=> Add logic to install Xcode-CLT if needed

.gitattributes, README.md
[links]:#
- Prevent Makefiles from getting into release archives (advanced users only)
- Added News section to README w/ content about trying OpenCoarrays online
- Don't include gasnet dir in …
=> Small fixes

src/mpi/CMakeLists.txt, src/mpi/mpi_caf.c
Based on tales of success by @jbmaggard in issue #435
Fixes #435
Error in the type def of an argument to `MPI_Type_extent`
`long int string_len;` → `MPI_Aint string_len;` on `mpi_caf.c:4140`
[L4140]: https://github.com/sourceryinstitute/OpenCoarrays/blob/f7a5f2ebeaf935a67184a978bc40177e4399b82b/src/mpi/mpi_caf.c#L4140
[links]:# …
=> Fix bug & improve Windows support

CMakeLists.txt, src/libcaf-gfortran-descriptor.h, src/mpi/mpi_caf.c
[links]:#
Update libcaf header for new component in array descriptor
GCC 8.x added a new component to the array descriptor struct and if we don't match it, the OC tests fail
This pull request (PR) …
=> Descriptor fix

prerequisites/build-functions/download_if_necessary.sh
[links]:#
Edited the file name that `install.sh` uses to detect previously downloaded GCC branches.
With GCC branch downloads, the URL tail has the prefix `branches/`, which needs to be deleted …
=> install.sh now detects present GCC branch tar ball

CMakeLists.txt, src/extensions/caf.in
- Also fix issue in CAF script arising from the use of FC=mpifort
[links]:#
Very small tweak to correctly handle the case when users pass `FC=mpifort CC=mpicc` and deprecation warning message if …
=> Issue deprecation warning for FC=mpifort

prerequisites/build-functions/set_or_print_default_version.sh
[links]:#
Incremented the default GCC version that `./install.sh -p gcc` installs to 7.3.0.
7.3.0 contains regression fixes for allocatable components of derived-type coarrays.
This pull request …
=> Bump GCC version that install.sh installs to 7.3.0

src/libcaf-gfortran-descriptor.h, src/libcaf-version-def.h, src/libcaf.h, src/make.inc, src/mpi/mpi_caf.c, src/tests/integration/pde_solvers/coarrayHeatSimplified/Makefile
[links]:#
Updated MPI library for new descriptor.
Without these changes, widespread failures occur with GCC 8.
- …
=> Adjust for the Fortran 2018 descriptors

src/libcaf-gfortran-descriptor.h, src/mpi/mpi_caf.c
- Issue with a type_def persists; non-constant member does not appear last
[links]:#
Fixed most warnings/errors when compiling with Clang. Problematic struct (GNU extension) remains and requires …
=> Fix most warnings when compiling w/ clang

CMakeLists.txt, src/tests/regression/reported/CMakeLists.txt, src/tests/regression/reported/issue-493-coindex-slice.f90
Ensures no regressions of #493 are encountered when slicing multi-
codimensioned coarrays
[links]:#
Add test from #493 fixed in PR #495 
Show @neok-m4700 changes needed to cmake to include tests, …
=> Add tests for issue #493 fixed by PR #495

src/mpi/CMakeLists.txt
ABI Changes on the GFortran side necesitate OC ABI changes
Fixes #489
[links]:#
Increment SO version for GFortran >= 8.x
Array descriptor and other ABI changes in GFortran 8.x
This pull request …
=> Bump SOVERSION if GFortran >= 8.x

src/extensions/caf.in, src/extensions/cafrun.in, src/mpi/CMakeLists.txt
CMake uses semi-colons to separate list items, and some of these
semicolons were being injected into the `caf` script on some systems
(FreeBSD) where as spaces should have been used. (See #475, specifically
https://github.com/sourceryinstitute/OpenCoarrays/issues/475#issuecomment-364190210)
[links]:# …
=> Use ` `, not `;`, field sep when configuring `caf`

src/libcaf-gfortran-descriptor.h, src/libcaf.h, src/mpi/mpi_caf.c
GFortran 8.x uses size_t for character lengths instead of int. This
patch applies the same changes to OpenCoarrays. Also, the STOP and
ERROR STOP routines now take a plain int for the numeric exit code.
This fixes
https://github.com/sourceryinstitute/OpenCoarrays/issues/497.
does not already exist a related test that failed before the PR
- At least maintaining test coverage for all other PRs
- Ensuring that all tests pass when run locally 
- Naming PR  to indicate work in progress (WIP) and to attach the PR
to the appropriate bug report or feature request [issue]
- White space (no trailing white space or white space errors may
be introduced)
- …
=> Use size_t for character lengths with GFortran >= 8.x

prerequisites/build-functions/build_and_install.sh
[links]:#
Corrected the path for searching for patch files.
I discovered this while building gfortran 8.1.0 on the Raspberry Pi.  :)
Slash was truncated without being replaced.
This pull request …
=> Add slash in patch path in build_and_install.sh

.travis.yml, CMakeLists.txt, developer-scripts/travis/install.osx.sh, developer-scripts/travis/test-script.cmake.sh, src/CMakeLists.txt, src/mpi/CMakeLists.txt, src/mpi/mpi_caf.c, src/tests/unit/CMakeLists.txt
[links]:#
1. Fix errant output discussed [here](https://github.com/sourceryinstitute/OpenCoarrays/pull/555#issuecomment-401896724)
2. Never build `ISO_Fortran_binding.h` and friends unless …
=> Misc fixes

prerequisites/install-functions/find_or_install.sh
[links]:#
Update `prerequisites/install-functions/find_or_install.sh` so that the 2nd place where the compiler version is checked now passes the new argument expected by `acceptable_compiler.f90`. …
=> Fix 2nd place where installer checks compiler ver.

prerequisites/build-functions/set_or_print_url.sh
Each download has been tested using the -o download-only option such as
```
./install.sh -p gcc -o
```
[links]:#
Changed all prerequisite package `ftp` URLs to `https` mirror-site equivalents.
See …
=> Switch insecure ftp URLs to secure https

src/mpi/CMakeLists.txt, src/mpi/mpi_caf.c, src/openshmem/openshmem_caf.c
[links]:#
`MPI_Type_extent()` --> `MPI_Type_get_extent()`
The `MPI_Type_extent()` function is deprecated, and the build fails with newer MPI.
- Increasing test coverage …
=> Issue 586 deprecated mpi func

prerequisites/install-functions/find_or_install.sh
[links]:#
Replaced erroneous variable name in `prerequisites/install-functions/find_or_install.sh`.
In several places, an older name was being used for the bash variable `minimum_version`, …
=> Fix the installer's compiler-version check

prerequisites/install-functions/find_or_install.sh
Replaced erroneous variable name in `prerequisites/install-functions/find_or_install.sh`.
In several places, an older name was being used for the bash variable `minimum_version`, resulting in an attempt to evaluate an unset variable.
does not already exist a related test that failed before the PR
- At least maintaining test coverage for all other PRs
- Ensuring that all tests pass when run locally 
- Naming PR  to indicate work in progress (WIP) and to attach the PR
to the appropriate bug report or feature request [issue]
- White space (no trailing white space or white space errors may
be introduced)
- Commenting code where it is non-obvious …
=> Fix compiler min ver check

prerequisites/build-functions/build_and_install.sh, prerequisites/build-functions/set_or_print_default_version.sh
[links]:#
* Bump default/minimum GCC version to 8.3.0
* Facilitate `install.sh -p cmake -i <cmake-install-path>` with a cmake installation path that requires `sudo` privileges.
* GCC 8.3.0 was …
=> Installer updates

prerequisites/install-functions/report_results.sh, src/mpi/CMakeLists.txt
`caf` wrapper script defaults to static linkage against libcaf_mpi.a but if you're
building a shared lib with the `caf` script this fails because objects in `libcaf_mpi.a`
are not compiled with `-fPIC`. So creating shared libs fails.
The wrapper script should probably default to building and linking against the shared lib
[links]:# …
=> Use PIC for (default) static lib

prerequisites/install-functions/report_results.sh, src/extensions/opencoarrays.F90
[links]:#
|    | ![Codecov branch][coverage] |
~~Repeat is VERY broken in GFortran 8.3~~; work around using it.
Also, it produces object files with error messages embedded in them with links to the source directory even when compiling with `-fno-working-directory`. …
=> Gfortran non determinism repeat

.Dockerfiles/master-jupyter-inherit/hooks/build
- Extra/erroneous tags were being inserted when run on dockerhub infra
[links]:#
Dockerhub build hook (script)
So that pushes to master will build the docker image and that can be used to launch a jupyter-CAF-kernel binder notebook based on the master branch.
- I will wait at least 24 hours before self-approving the PR to give …
=> Fix dockerhub build hook

src/mpi/mpi_caf.c
[links]:#
`%d` ➡️ `%zd` in mpi_caf.c:7383
Silence clang warning:
```
/Users/ibeekman/Sandbox/OpenCoarrays/src/mpi/mpi_caf.c:7383:29: warning: format specifies type 'int' but the argument has type 'size_t' (aka 'unsigned long') [-Wformat]
printf("DTYPE Size: %d\n",GFC_DESCRIPTOR_SIZE(a));
~~    ^~~~~~~~~~~~~~~~~~~~~~
%zu
/Users/ibeekman/Sandbox/OpenCoarrays/src/libcaf-gfortran-descriptor.h:84:35: note: expanded from …
```
=> Fix clang warning about `%d` with `size_t`

src/mpi/mpi_caf.c
Since #630 is about to be closed due to staleness, I went ahead and implemented the minor change suggested in the RFE.
Remove the superfluous MPI_Barrier() that is called during the execution of a FORM TEAM statement.
MPI_Comm_split() alone is sufficient to provide image ordering semantics required by an image control statement like FORM TEAM.
- I have not introduced errant white space (no trailing white space or white space errors may
be introduced)
- I have added an explanation of what these changes do and why they should be included
- I have checked to ensure …
=> Implement RFE #630

INSTALL.md, README.md
- Repology provides version information for all available package mangers
[links]:#
- I have not introduced errant white space (no …
=> Add repology badge for package manager versions

prerequisites/build-functions/build_and_install.sh
[links]:#
With this PR, `install.sh` will set `FFLAGS="-w -fallow-argument-mismatch"` when building MPICH with GCC versions >= 10. 
GCC 10 reports an error when procedure arguments mismatch even in Fortran 77 procedures with implicit interfaces. …
=> fix #679: set FFLAGS for mpich configure with GCC >= 10

prerequisites/acceptable_compiler.f90
[links]:#
Improved `acceptable_compiler.f90`.
Previous version failed for double-digit major version numbers.
- I have not introduced errant white space (no trailing white space or white space …
=> Fix #683 check compiler version

CMakeLists.txt, src/mpi/CMakeLists.txt, src/tests/utilities/CMakeLists.txt
[links]:#
- mark target `opencoarrays_test_utilities` as static
- use generator expression to link to a generated library instead of hard coding the path
- fix typo
When building with `BUILD_SHARED_LIBS=ON` `opencoarrays_test_utilities` was
build as a shared library but in the function `caf_compile_executable`
it is hard coded as a static library. Thus leading to the build error described …
=> Fix static lib opencoarrays_test_utilities not found (issue  676)

src/mpi/CMakeLists.txt
[links]:#
- replaced string of space separated MPI compile flags in generator expression
in cmake function `target_compile_options` by a list
- used function `target_compile_definitions` for the compile definitions instead of appending
them to the compile options
The function `target_compile_options` in combination with
generator expressions does not handle strings with space
separated compiler flags and instead …
=> Fix MPI compile flags to not include quotation marks (issue-704)

CMakeLists.txt, INSTALL, LICENSE, install.sh-usage, prerequisites/acceptable_compiler.f90, prerequisites/build-functions/build_and_install.sh, prerequisites/build-functions/download_if_necessary.sh, prerequisites/build-functions/set_or_print_default_version.sh, prerequisites/build-functions/set_or_print_downloader.sh, prerequisites/build-functions/set_or_print_url.sh, prerequisites/build.sh-usage, prerequisites/check_version.sh, src/mpi/CMakeLists.txt, src/tests/utilities/CMakeLists.txt
[links]:#
Set `install.sh` to default to building GCC 10.1.0 if an earlier version is detected and no other version is specified.  This can still be over-rided for users who want to build OpenCoarrays with an older version by passing the `-f`, `-c`, and `-C` arguments (or their longer equivalents).
1. This ensures co_broadcast handles derived type arguments.
2. This also updates the gcc download to use `git` because …
=> Update GCC default-minimum version to 10.1.0 & fix compiler version check

src/mpi/mpi_caf.c
[links]:#
Corrected/Improved handling of va_args in runtime error messages. 
The previous version present some odd numbers for arguments instead of the values expected. Furthermore was the code in several place clearly wrong, which fortunately did not lead to crashes yet.
- I will wait at least 24 hours before self-approving the …
=> Correct/Improve handling of runtime errors.

.VERSION, src/extensions/cafrun.in
[links]:#
Fixed #717 
`cafrun` exited quietly when no number of images was specified, e.g., `cafrun ./a.out`.
- I have not introduced errant white space (no trailing white space or white space …
=> Fix #717 cafrun usage message

prerequisites/install-functions/build_opencoarrays.sh, prerequisites/install-functions/report_results.sh
[links]:#
Updated the installation scripts to allow for `mpifort` invoking `gfortran` via `f95`.
On Lubuntu 20.04, `sudo apt install mpich` results in `mpifort -show` returning a command that starts with `f95` instead of `gfortran`, which previously caused the installer to fail to recognize that `mpifort` wraps `gfortran`.  
- I …
=> fix(installer): handle mpifort invoking f95

prerequisites/build-functions/set_or_print_downloader.sh, prerequisites/build-functions/set_or_print_url.sh
[links]:#
`install.sh` now downloads GCC tar balls instead of cloning GCC release branches.
Downloading release tar balls is much faster than cloning branches.
- I have not introduced errant …
=> feat(install.sh): download GCC release tar balls

src/tests/unit/simple/random_init.f90
Fix compile warnings about Logical to Integer conversions using the
transfer()-function.
[links]:#
Fix compile warnings LOGICAL -> INT
Get rid of occurring compile warnings.
- I have not …
=> Fix compile warnings LOGICAL -> INT

src/mpi/CMakeLists.txt
I'd like to get the CI system back up to parity with the old Travis-CI system. If I have time I'll add this to this PR, otherwise I'll change this from a draft to a real PR and just commit what's here.
Unfortunately mpi_caf.c now calls into libgfortran for the random seed
functionality.
It would be nice to avoid this if possible, but it's stateful so I
doubt that it would be possible.
Any code that links to the library should be Fortran code and/or pull in libgfortran.
[links]:# …
=> Use dynamic symbol resolution for libmpi_caf on macOS

src/runtime-libraries/mpi/mpi_caf.c
[links]:#
Fix imbalanced calloc/MPI_free_mem.
Memory allocated by calloc was errorneously freeed using MPI_free_mem,
which might confuse Intel MPI. This should fix a bit more of #762.
- I have …
=> Fix imbalanced calloc/MPI_free_mem.

CMakeLists.txt
Using of single quotes for `printf` argument within MPI_C check of CMakeLists.txt results in warning of conversion to int. The single quotes is used for char/int but not for char* type where the double quotes should be used.
If clang is used as MPI_C instead of gcc the configuration is failed with error:
`incompatible integer to pointer conversion passing 'int' to parameter of type 'const char *' [-Wint-conversion]`
(refer Gentoo [guru overlay] issue:[https://bugs.gentoo.org/888009]( https://bugs.gentoo.org/888009))
[links]:#
[coverage]: https://img.shields.io/codecov/c/github/sourceryinstitute/OpenCoarrays/master.svg?sty …
=> CMake: fix -Wint-conversion warning (error if clang is used as MPIC_C)

src/runtime-libraries/mpi/mpi_caf.c, src/tests/unit/send-get/send_convert_nums.f90
[links]:#
Correctly copy data when sending to this_image.
Sending data to this_image() lead to doing a memmove even when that was unsuitable, because size, rank, type, a.s.o. did not match. This patch directs all data sends to the convert routine, which does scalar to array and type/kind conversion correctly.
- I will wait at …
=> Fix sending data to self.

.VERSION, src/CMakeLists.txt, src/runtime-libraries/mpi/mpi_caf.c, src/script-templates/caf.in, src/tests/integration/pde_solvers/coarrayBurgers/CMakeLists.txt, src/tests/integration/pde_solvers/coarrayHeatSimplified/CMakeLists.txt, src/tests/integration/pde_solvers/coarrayHeatSimplified/global_field.f90, src/tests/integration/pde_solvers/coarrayHeatSimplified/local_field.f90, src/tests/integration/pde_solvers/coarrayHeatSimplified/main.f90, src/tests/unit/send-get/send_convert_nums.f90, src/tests/utilities/CMakeLists.txt, src/tests/utilities/opencoarrays_object_interface.f90
[links]:#
Fix build dependencies to enable parallel builds.
While figuring issues in OpenCoarrays fast builds are reQuired to reduce turn-around time when switching mpi-library. The build system was only allowing seQuential builds using make. The patches in this pr fix this for `make -j N` and `ninja`. Other build systems might benefit, too. This may allow for easier implementing #759, but will not fix it completely. …
=> Fix parallel build issues

.clang-format, CMakeLists.txt, developer-scripts/git-hooks/pre-commit, src/application-binary-interface/libcaf-gfortran-descriptor.h, src/application-binary-interface/libcaf.h, src/runtime-libraries/mpi/mpi_caf.c
[links]:#
Unify formatting of C sources utilizing a tool available on all platforms.
Editing the sources always lead to indentation and formatting getting ugly or I had to manually fix the formatting my IDE did. I therefore opted to use a tool (clang-format) that is widely available and can be configured to have the code look very similar to the previous version. Furthermore does is support partial formatting in …
=> Add clang-formating for c sources and headers.
